name: daily_list
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  easy_localization: ^3.0.8
  flutter_svg: ^2.2.0
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  cloud_firestore: ^6.0.0
  freezed_annotation: ^3.1.0
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  json_annotation: ^4.9.0
  get_it: ^8.2.0
  injectable: ^2.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.8.1
  flutter_lints: ^5.0.0
  build_runner: ^2.7.0
  freezed: ^3.2.0
  json_serializable: ^6.11.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/translations/
  fonts:
    - family: PoppinsBlack
      fonts:
        - asset: assets/fonts/Poppins-Black.ttf
    - family: PoppinsBold
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
    - family: PoppinsExtraBold
      fonts:
        - asset: assets/fonts/Poppins-ExtraBold.ttf
    - family: PoppinsExtraLight
      fonts:
        - asset: assets/fonts/Poppins-ExtraLight.ttf
    - family: PoppinsLight
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
    - family: PoppinsMedium
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
    - family: PoppinsRegular
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
    - family: PoppinsSemiBold
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf
